export const SERVICE_PAGES = [
    {
        id: 'marketing',
        num: '01',
        name: 'Marketing',
        tone: '#6082B6',
        does: 'Gets a brand in front of the people who should already know it.',
        why: 'The work only lands if it shows up where people already are.',
        items: ['Organic Marketing', 'Advertisement', 'Lead Generation', 'Social Media', 'Performance', 'Content'],
    },
    {
        id: 'design',
        num: '02',
        name: 'Design',
        tone: '#6082B6',
        does: 'Gives the brand a look that holds from the logo to the screen.',
        why: 'If the pieces do not match, the brand feels like five vendors.',
        items: ['Logo Design', 'Brand Guides', 'Website Design', 'App Design', 'UX Design', '3D Designing'],
    },
    {
        id: 'video',
        num: '03',
        name: 'Video Production',
        tone: '#367588',
        does: 'Plans the shoot, films it, and cuts it so it can live on the feed.',
        why: 'A film that cannot travel is a file. This is the piece people send around.',
        items: ['Corporate', 'Lifestyle', 'Food', 'Product', 'Shoot Strategy', 'Video Editing'],
    },
    {
        id: 'web',
        num: '04',
        name: 'Web Development',
        tone: '#003153',
        does: 'Builds the site or product the campaign actually points to.',
        why: 'The campaign and the product should come from the same team.',
        items: ['E-Commerce', 'Landing Pages', 'CMS', 'Mobile Apps', 'Personal Sites', 'Custom Products'],
    },
    {
        id: 'automation',
        num: '05',
        name: 'Automation',
        tone: '#082567',
        does: 'Keeps the follow-up moving after the campaign is live.',
        why: 'Leads, reports, and replies should not depend on someone remembering.',
        items: ['Workflows', 'CRM Setup', 'Lead Routing', 'Reporting', 'Integrations', 'Chat Flows'],
    },
];

export const CASES = [
    {
        slug: 'growth-lab',
        num: '01',
        client: 'Growth Lab',
        title: 'Growth Lab',
        accent: 'The reel people finish.',
        category: 'Video',
        services: ['Video', 'Motion', 'Social'],
        hero: { type: 'video', src: '/work/video-growth-lab.mp4', poster: '/work/poster-growth-lab.jpg' },
        cover: '/work/poster-growth-lab.jpg',
        shots: ['/work/poster-growth-lab.jpg', '/work/brand-growth-lab.jpg'],
        brief: 'A coaching brand needed a reel that felt like the product — sharp, paced, and made to be watched to the end. Not a logo sting. A piece of film for the feed.',
        made: 'FivePS cut the Growth Lab reel in-house: motion, type, and the edit sitting in one file. The poster and the brand mark were built to match, so the still and the film feel like the same agency.',
        note: 'This is the work playing on the FivePS site. No invented reach number sits on top of it.',
    },
    {
        slug: 'fiveps-motion',
        num: '02',
        client: 'FivePS',
        title: 'FivePS motion',
        accent: 'A mark that has to move.',
        category: 'Identity',
        services: ['Logo', 'Motion', 'Identity'],
        hero: { type: 'video', src: '/work/video-digital-logo.mp4', poster: '/work/poster-digital-logo.jpg' },
        cover: '/work/poster-digital-logo.jpg',
        shots: ['/work/poster-digital-logo.jpg', '/work/brand-fiveps.jpg'],
        brief: 'The agency needed a logo that still reads at 24px and still holds when it moves. Most marks die in a story. This one had to live there.',
        made: 'The FivePS identity was drawn, then put into motion. The film is the logo working — not a decoration around it.',
        note: 'Same file as the motion on the home and portfolio reels.',
    },
    {
        slug: 'fiveps-website',
        num: '03',
        client: 'FivePS',
        title: 'FivePS website',
        accent: 'The agency, on a page.',
        category: 'Website',
        services: ['Website', 'Design'],
        hero: { type: 'image', src: '/work/site-home.jpg' },
        cover: '/work/site-home.jpg',
        shots: ['/work/site-home.jpg', '/work/site-services.jpg', '/work/site-fiveps-in.jpg'],
        brief: 'The live site had to look like the work, not like a brochure about the work. Home, services, and the older fiveps.in frames all sit in this file.',
        made: 'Pages for the agency: the home, the services view, and the existing fiveps.in screen. Built so a brief and a reel point to the same brand.',
        note: 'These are real screens from FivePS properties — not stock layouts.',
    },
    {
        slug: 'adis-farm',
        num: '04',
        client: "Adi's Farm",
        title: "Adi's Farm",
        accent: 'A farm that looks like itself.',
        category: 'Branding',
        services: ['Branding', 'Campaign'],
        hero: { type: 'image', src: '/work/end-adis-farm.jpg' },
        cover: '/work/end-adis-farm.jpg',
        shots: ['/work/end-adis-farm.jpg', '/work/brand-adis-farm.jpg'],
        brief: 'A farm brand needs to feel like produce and land — not like a city agency dressed it. The identity and the end-frame had to hold together.',
        made: 'The Adi’s Farm mark, and the campaign still that sits with it. One agency for both, so the bag and the post don’t feel like two vendors.',
        note: 'Real client work. No made-up harvest statistic.',
    },
    {
        slug: 'nu-look',
        num: '05',
        client: 'Nu Look',
        title: 'Nu Look',
        accent: 'A look that holds on the feed.',
        category: 'Campaign',
        services: ['Branding', 'Social'],
        hero: { type: 'image', src: '/work/end-nu-look.jpg' },
        cover: '/work/end-nu-look.jpg',
        shots: ['/work/end-nu-look.jpg', '/work/brand-nu-look.jpg'],
        brief: 'Nu Look needed a presence that feels finished — identity and the piece people actually post. The still and the mark had to agree.',
        made: 'Brand work and the campaign end-frame, cut to sit in a feed without looking like a leftover from a print job.',
        note: 'What you see is the file. Not a claimed conversion rate.',
    },
    {
        slug: 'solartouch',
        num: '06',
        client: 'Solartouch',
        title: 'Solartouch',
        accent: 'Energy, made visible.',
        category: 'Campaign',
        services: ['Campaign', 'Branding'],
        hero: { type: 'image', src: '/work/end-solartouch.jpg' },
        cover: '/work/end-solartouch.jpg',
        shots: ['/work/end-solartouch.jpg', '/work/end-solar.jpg', '/work/brand-solartouch.jpg'],
        brief: 'A solar brand has to look like power and trust, not like a clip-art sun. The campaign frames and the mark needed the same weight.',
        made: 'Campaign stills and the Solartouch identity, so the post and the board don’t drift apart.',
        note: 'Real Solartouch work in the FivePS archive.',
    },
];

export const PORTFOLIO = CASES;

export const POSTS = [
    {
        slug: 'start-with-the-brief',
        title: 'Start with the brief',
        category: 'Agency',
        date: 'From the agency',
        time: '3 min',
        featured: true,
        excerpt: 'The size of the company does not decide the work. The brief does.',
        cover: '/work/brand-fiveps.jpg',
        body: [
            'FivePS takes a job from the first conversation. The brief decides the shape — not a menu of packages pretending to be strategy.',
            'That is why the agency keeps strategy, ads, content, design and websites in one place. If those sit with five vendors, the brand starts to look like five vendors.',
            'Send the brief. We reply with the approach, what is in it, and when it can start.',
        ],
    },
    {
        slug: 'one-founder-one-roof',
        title: 'One founder. One roof.',
        category: 'Agency',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'The brief goes to the person who built the agency — not a pile of partners.',
        cover: '/work/site-fiveps-in.jpg',
        body: [
            'FivePS is Pankaj’s company. That is not a slogan. It is how the work is run: one founder, one agency, one place the brief lands.',
            'Clients do not get handed between a strategy shop, a design shop and an ads shop. The same roof holds the plan, the ads, the content and the follow-up.',
            'If you want to talk to the person who built it, write to hello@fiveps.com.',
        ],
    },
    {
        slug: 'the-work-sits-here',
        title: 'The work sits here',
        category: 'Agency',
        date: 'From the agency',
        time: '2 min',
        excerpt: 'Strategy, ads, content, design and websites. One archive.',
        cover: '/work/site-services.jpg',
        body: [
            'A new brief should sit next to work that already exists. That only happens if the files live in one agency.',
            'The FivePS website frames, the campaign stills, and the motion files are kept together so a farm, a clinic, or a dealership can borrow the same craft — not the same template.',
            'This is why the portfolio and the case studies point at real files, not a moodboard.',
        ],
    },
    {
        slug: 'organic-is-not-a-hobby',
        title: 'Organic is not a hobby',
        category: 'Marketing',
        date: 'From the agency',
        time: '4 min',
        excerpt: 'A feed without a plan is just posting. A plan without a feed is a deck.',
        cover: '/work/brand-growth-lab.jpg',
        body: [
            'Organic work is the part people see when they are not being asked to click. It has to look like the brand on a quiet Tuesday, not only on launch week.',
            'FivePS treats organic as part of the system: voice, stills, film, and the rhythm they show up in. Not a junior dumping graphics after the “real” campaign is done.',
            'If the organic and the ads disagree, the audience believes neither.',
        ],
    },
    {
        slug: 'ads-need-somewhere-to-land',
        title: 'Ads need somewhere to land',
        category: 'Marketing',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'A click with nowhere to go is money spent on a shrug.',
        cover: '/work/brand-waaree.jpg',
        body: [
            'Performance without a page is a leak. The ad can be sharp and the lead still dies if the next screen feels like another company.',
            'That is why marketing and web sit under the same roof here. The campaign and the landing should be drawn together, not taped after the media plan is locked.',
            'Start with where the click goes. Then buy the attention.',
        ],
    },
    {
        slug: 'lead-gen-is-a-system',
        title: 'Lead gen is a system',
        category: 'Marketing',
        date: 'From the agency',
        time: '4 min',
        excerpt: 'A form is not a pipeline. The follow-up is.',
        cover: '/work/brand-solartouch.jpg',
        body: [
            'Leads do not become work because a form existed. They become work when someone answers, routes, and remembers.',
            'FivePS builds the capture and the follow-up as one job: the ad, the page, the CRM, the reply. If any piece lives in a different shop, the lead waits.',
            'Ask for the brief if you want that chain built, not a lead magnet pdf.',
        ],
    },
    {
        slug: 'the-first-audience',
        title: 'The first audience',
        category: 'Marketing',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'Startups and established brands sit in the same agency. The brief decides.',
        cover: '/work/brand-adis-farm.jpg',
        body: [
            'Some brands are still looking for the people who should already know them. Some already have an audience and need the work to catch up.',
            'FivePS does both. The size of the company does not pick the tools. The brief does.',
            'Farms, clinics, dealerships, event studios, founders — the work changes shape. The roof does not.',
        ],
    },
    {
        slug: 'a-logo-at-24px',
        title: 'A logo that still reads at 24px',
        category: 'Design',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'Most marks die in a story. This one has to live there.',
        cover: '/work/poster-digital-logo.jpg',
        body: [
            'A mark that only works on a letterhead is half a mark. It has to hold in a highlight, a tab, a reel, a tiny stamp on a site.',
            'The FivePS identity was drawn, then put into motion, for that reason. If it cannot move and still read, it is decoration.',
            'Design here starts with where the mark will actually sit — not with a presentation board.',
        ],
    },
    {
        slug: 'brand-guides-nobody-opens',
        title: 'Brand guides nobody opens',
        category: 'Design',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'A 40-page PDF is not a brand. The next post is.',
        cover: '/work/brand-belle-ame.jpg',
        body: [
            'Guides are useful when the people making the work will actually use them. Most of them sit in a drive.',
            'FivePS would rather leave you with files that already agree: the logo, the type, the still, the reel, the page. The guide, if it exists, describes what is already in motion.',
            'If the pieces match in the feed, you do not need a lecture about them.',
        ],
    },
    {
        slug: 'if-the-pieces-dont-match',
        title: 'If the pieces don’t match',
        category: 'Design',
        date: 'From the agency',
        time: '2 min',
        excerpt: 'The brand starts to feel like five vendors.',
        cover: '/work/brand-nu-look.jpg',
        body: [
            'A logo from one shop, a site from another, ads from a third. People can tell. They do not call it “inconsistent.” They just do not trust it.',
            'The job of design at FivePS is to hold from the mark to the screen so nothing feels taped on.',
            'That is a design problem and an agency problem. Same desk.',
        ],
    },
    {
        slug: 'ux-is-the-brief-on-a-screen',
        title: 'UX is the brief on a screen',
        category: 'Design',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'If the page fights the campaign, the campaign loses.',
        cover: '/work/end-nu-look.jpg',
        body: [
            'UX is not a separate religion. It is the brief, laid out so a person can finish the thought.',
            'Buttons, type, the order of the story — they either carry the work or they trip it. FivePS designs the page with the same people who made the campaign.',
            'If you only need a prettier wireframe, this is the wrong agency.',
        ],
    },
    {
        slug: 'a-reel-people-finish',
        title: 'A reel people finish',
        category: 'Video',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'Not a logo sting. A piece of film for the feed.',
        cover: '/work/poster-growth-lab.jpg',
        body: [
            'The Growth Lab reel was cut to be watched to the end. Pace, type, motion — one file, in-house.',
            'A film that cannot travel is a file. The still and the cut have to feel like the same agency, so the poster is not a different brand from the video.',
            'Two real films sit in the work: Growth Lab, and the FivePS mark in motion. That is the bar.',
        ],
    },
    {
        slug: 'film-that-can-travel',
        title: 'Film that can travel',
        category: 'Video',
        date: 'From the agency',
        time: '4 min',
        excerpt: 'Corporate, lifestyle, food, product — the cut still has to move.',
        cover: '/work/end-euler.jpg',
        body: [
            'A corporate film and a food reel are different jobs. They are not different standards.',
            'FivePS plans the shoot, films it, and cuts it so it can live on the feed — not only on a USB after the event.',
            'If it cannot sit in a story next to the identity, it is not finished.',
        ],
    },
    {
        slug: 'the-still-and-the-cut',
        title: 'The still and the cut',
        category: 'Video',
        date: 'From the agency',
        time: '2 min',
        excerpt: 'The poster and the film should be the same thought, paused.',
        cover: '/work/brand-euler-retro.jpg',
        body: [
            'A thumbnail that lies about the film trains people to skip you. A film that looks nothing like the still trains them not to click.',
            'We build the poster with the edit, not after it. Same type, same colour, same pace in the first frame.',
            'That is why the work archive keeps the still next to the motion file.',
        ],
    },
    {
        slug: 'shoot-strategy-first',
        title: 'Shoot strategy first',
        category: 'Video',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'The camera is late if the story is not decided.',
        cover: '/work/end-yashika.jpg',
        body: [
            'A shoot without a story is expensive footage. The plan has to know where the film will live: reel, site, ad, the room.',
            'FivePS writes that plan before the kit leaves. Editing is not where we invent the brief.',
            'If you already have rushes, we can still cut. If you have a brief, we can still shoot. Both are work. One is cleaner.',
        ],
    },
    {
        slug: 'the-campaign-needs-a-page',
        title: 'The campaign needs a page',
        category: 'Web',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'The site is not a leftover. It is where the click has to finish.',
        cover: '/work/end-solartouch.jpg',
        body: [
            'People still land somewhere. If that somewhere was built by a different team, the campaign feels like a bait.',
            'Landing pages, shops, personal sites, custom products — FivePS builds the thing the work points to.',
            'The campaign and the product should come from the same team. That is the whole note.',
        ],
    },
    {
        slug: 'landing-pages-that-hold',
        title: 'Landing pages that hold',
        category: 'Web',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'One job per page. The rest is decoration.',
        cover: '/work/end-solar.jpg',
        body: [
            'A landing page that tries to be the whole company is a brochure. A page that does one job — book, buy, enquire — can be short and still feel like the brand.',
            'We design that page with the ad, not against it. Same headline thought. Same proof. Same next step.',
            'If you need a 12-page site, say so. If you need one page that holds a campaign, say that too.',
        ],
    },
    {
        slug: 'ecommerce-is-still-a-brand',
        title: 'E-commerce is still a brand',
        category: 'Web',
        date: 'From the agency',
        time: '4 min',
        excerpt: 'A cart that looks like a plugin is a cart people leave.',
        cover: '/work/brand-param.jpg',
        body: [
            'Shops fail in the details people touch: type, photos, the button, the empty state. Those are design and development in the same week.',
            'FivePS builds e-commerce as part of the brand, not as a theme with a logo dropped in.',
            'The product photography, the film, and the page should agree. Otherwise the checkout feels like a different shop.',
        ],
    },
    {
        slug: 'follow-up-should-not-wait',
        title: 'Follow-up should not wait',
        category: 'Automation',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'Leads, reports, and replies should not depend on someone remembering.',
        cover: '/work/brand-anand-dental.jpg',
        body: [
            'A campaign that dumps names into a sheet is unfinished. The routing, the reply, the reminder — that is the work after the work.',
            'FivePS sets workflows, CRM, lead routing and reporting so the agency and the client are not the bottleneck.',
            'Automation here is not a chatbot for its own sake. It is the follow-up moving while people are busy making the next thing.',
        ],
    },
    {
        slug: 'crm-is-not-a-spreadsheet',
        title: 'CRM is not a spreadsheet',
        category: 'Automation',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'If the pipeline lives in someone’s download folder, it is already lost.',
        cover: '/work/brand-retro-insurance.jpg',
        body: [
            'Spreadsheets hide. CRMs, when they are set up for the actual brief, show who waited and who was answered.',
            'We set the tool to the process, not the other way around. Clinics, dealerships and founders do not need the same fields.',
            'If you already have a CRM that nobody opens, that is still a brief.',
        ],
    },
    {
        slug: 'reporting-without-theatre',
        title: 'Reporting without theatre',
        category: 'Automation',
        date: 'From the agency',
        time: '2 min',
        excerpt: 'A dashboard is useful when it answers the brief. The rest is decoration.',
        cover: '/work/brand-rr.jpg',
        body: [
            'Reports that exist to look busy are worse than no reports. FivePS wires the numbers the brief actually cares about.',
            'Integrations, lead routing, a weekly view — enough to decide the next move. Not a wallpaper of charts.',
            'If a number cannot change the work, it does not need a tile.',
        ],
    },
    {
        slug: 'feed-and-the-brand',
        title: 'The feed and the brand',
        category: 'Brand',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'If the logo and the reel don’t match, nobody believes either of them.',
        cover: '/work/brand-call-of-the-blue.jpg',
        body: [
            'A mark that cannot live in a story is only half a mark. A reel that does not look like the identity is only content.',
            'FivePS cuts identity and motion together for that reason. The Growth Lab reel and the FivePS logo film are both in the work because they had to move and still read as the brand.',
            'Brand is what people meet. The book can wait.',
        ],
    },
    {
        slug: 'identity-that-moves',
        title: 'Identity that moves',
        category: 'Brand',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'A static mark is a start. The feed will ask it to work.',
        cover: '/work/brand-fiveps.jpg',
        body: [
            'The FivePS motion mark exists because the agency had to watch its own logo in a story. Most clients will have to do the same.',
            'We draw the identity, then we put it in motion, then we put it on the page. That order keeps the brand from splitting into “print” and “digital.”',
            'If your mark only works in a square on a wall, it is not ready for the work you hired us for.',
        ],
    },
    {
        slug: 'real-brands-not-a-moodboard',
        title: 'Real brands, not a moodboard',
        category: 'Brand',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'Clinics, farms, dealerships, event studios, founders. The work is already in the archive.',
        cover: '/work/brand-yaduvanshi.jpg',
        body: [
            'FivePS has already sat with 250+ brands. That number is not a trophy wall. It is the reason the agency does not invent a fake client list.',
            'The stills on this site are the work: Adis Farm, Nu Look, Solartouch, Anand Dental, and the rest. Look at those before you look at a trend board.',
            'Your brief will not be a remix of someone else’s. It will sit in the same archive.',
        ],
    },
    {
        slug: 'where-the-work-shows',
        title: 'Where the work shows up',
        category: 'Social',
        date: 'From the agency',
        time: '2 min',
        excerpt: 'The post, the site, and the film should feel like they came from the same desk.',
        cover: '/work/brand-shyam-event.jpg',
        body: [
            'People do not meet a brand in a brand book. They meet it in a reel, on a page, in a story, on a board.',
            'That is the job: make those surfaces agree. The FivePS website frames, the campaign stills, and the motion files are kept in one archive so a new brief can sit next to work that already exists.',
            'If you want the next piece to exist, send the brief.',
        ],
    },
    {
        slug: 'stories-are-not-leftovers',
        title: 'Stories are not leftovers',
        category: 'Social',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'A story is a place the brand has to work at 9:16, for a few seconds.',
        cover: '/work/brand-nihaal.jpg',
        body: [
            'Treating stories as the scrap of the campaign is how brands look tired by Wednesday.',
            'FivePS cuts stories with the same type and pace as the reel, because that is where a lot of people actually look.',
            'If it cannot hold for three seconds in a story, it is not ready for the grid either.',
        ],
    },
    {
        slug: 'the-room-and-the-feed',
        title: 'The room and the feed',
        category: 'Social',
        date: 'From the agency',
        time: '3 min',
        excerpt: 'The work only lands if it shows up in the feed, on the site, and in the room.',
        cover: '/work/brand-shree-shyam.jpg',
        body: [
            'Online is not a separate company. A board in a clinic, a reel on a phone, a site on a laptop — same brand, different furniture.',
            'Social at FivePS is not “content.” It is the brand showing up where people already are.',
            'That is why the agency will not split social from design from the site. The room and the feed have to recognise each other.',
        ],
    },
    {
        slug: 'content-is-the-work',
        title: 'Content is the work',
        category: 'Social',
        date: 'From the agency',
        time: '4 min',
        excerpt: 'A calendar full of posts is not a voice. A voice with a calendar can last.',
        cover: '/work/brand-bmr6.jpg',
        body: [
            'Content without a voice is volume. Voice without a rhythm disappears.',
            'We write and shoot for the actual surfaces: grid, story, reel, the site that catches the click. Same desk as the ads, so the paid and the organic do not argue.',
            'If you already post and it does not look like you, that is a brief. If you do not post yet, that is also a brief.',
        ],
    },
];
