export const SERVICE_PAGES = [
    {
        id: 'marketing',
        num: '01',
        name: 'Marketing',
        tone: '#6082B6',
        does: 'Gets a brand in front of the people who should already know it.',
        why: 'The work only lands if it shows up where people already are.',
        items: ['Organic Marketing', 'Advertisement', 'Lead Generation', 'Social Media', 'Performance', 'Content'],
    },
    {
        id: 'design',
        num: '02',
        name: 'Design',
        tone: '#5D8AA8',
        does: 'Gives the brand a look that holds from the logo to the screen.',
        why: 'If the pieces do not match, the brand feels like five vendors.',
        items: ['Logo Design', 'Brand Guides', 'Website Design', 'App Design', 'UX Design', '3D Designing'],
    },
    {
        id: 'video',
        num: '03',
        name: 'Video Production',
        tone: '#367588',
        does: 'Plans the shoot, films it, and cuts it so it can live on the feed.',
        why: 'A film that cannot travel is a file. This is the piece people send around.',
        items: ['Corporate', 'Lifestyle', 'Food', 'Product', 'Shoot Strategy', 'Video Editing'],
    },
    {
        id: 'web',
        num: '04',
        name: 'Web Development',
        tone: '#003153',
        does: 'Builds the site or product the campaign actually points to.',
        why: 'The campaign and the product should come from the same team.',
        items: ['E-Commerce', 'Landing Pages', 'CMS', 'Mobile Apps', 'Personal Sites', 'Custom Products'],
    },
    {
        id: 'automation',
        num: '05',
        name: 'Automation',
        tone: '#082567',
        does: 'Keeps the follow-up moving after the campaign is live.',
        why: 'Leads, reports, and replies should not depend on someone remembering.',
        items: ['Workflows', 'CRM Setup', 'Lead Routing', 'Reporting', 'Integrations', 'Chat Flows'],
    },
];

export const PORTFOLIO = [
    {
        num: '01',
        title: 'Videos',
        category: 'Film',
        wide: true,
        kind: 'video',
        src: 'https://videos.pexels.com/video-files/3209828/3209828-hd_1920_1080_25fps.mp4',
        text: 'The film reel already playing in the work section on the home page.',
    },
    {
        num: '02',
        title: 'Graphic',
        category: 'Still',
        wide: false,
        kind: 'image',
        src: 'https://cdn.prod.website-files.com/683703490bc01e1b8c052e06/686b8e614494dac669a4099c_c310914b5a1a573b4c7499e9531f8d52_DE.avif',
        text: 'A still from the graphic slider on the home page.',
    },
    {
        num: '03',
        title: 'Pages',
        category: 'Editorial',
        wide: false,
        kind: 'image',
        src: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=80',
        text: 'A page frame from the pages slider on the home page.',
    },
    {
        num: '04',
        title: 'Website',
        category: 'Product',
        wide: true,
        kind: 'image',
        src: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=1600&q=80',
        text: 'A website frame from the website slider on the home page.',
    },
];

export const POSTS = [
    {
        slug: 'placeholder-feed',
        title: 'Placeholder — the feed and the brand',
        category: 'Placeholder',
        date: 'Date to be added',
        time: '— min',
        featured: true,
        excerpt: 'This slot is waiting for a real FivePS note. It is not a published article.',
    },
    {
        slug: 'placeholder-brief',
        title: 'Placeholder — start with the brief',
        category: 'Placeholder',
        date: 'Date to be added',
        time: '— min',
        featured: false,
        excerpt: 'Structure only. Replace this card when a real note is ready.',
    },
    {
        slug: 'placeholder-ship',
        title: 'Placeholder — where the work shows up',
        category: 'Placeholder',
        date: 'Date to be added',
        time: '— min',
        featured: false,
        excerpt: 'Structure only. No invented story behind this title.',
    },
];
